Fixed zsh configuration.

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -29,18 +29,19 @@ safeln()
             echo "Unable to override: $2" >&2 && exit 1
         fi
     fi
-    ln -s "$1" "$2"
+    ln -vs "$1" "$2"
 }
 
 saferm()
 {
+    local i
     for i
     do
         if [[ -h $i ]]
         then
-            rm -f "$i"
+            rm -vf "$i"
         else
-            echo "Unable to remove: $2" >&2 # not fatal
+            echo "Unable to remove: $i" >&2 # not fatal
         fi
     done
 }
@@ -49,7 +50,7 @@ install()
 {
     for i
     do
-        fname="$(basename "$i")"
+        local fname="$(basename "$i")"
         safeln "$i" "$HOME/$fname"
         echo "$fname" >>"$current_install_file"
     done
@@ -65,6 +66,7 @@ cinstall()
 
 uninstall()
 {
+    local f
     for f in "${install_files[@]}"
     do
         if [[ -e $f ]]
@@ -106,6 +108,13 @@ if [[ -z $only_uninstall ]]
 then
     install \
         "$suffix/.z"* \
+
+    if [[ -d $suffix/$HOST ]]
+    then
+        install \
+            "$suffix/local/$(hostname)/.z"* \
+
+    fi
 
     cinstall \
         bin \
